// Code generated by Slice Machine. DO NOT EDIT.

import GridSlice from './GridSlice';
import HeroSlice from './HeroSlice';
import NavigationItem from './NavigationItem';
import ProjectListSlice from './ProjectListSlice';
import SectionSlice from './SectionSlice';

export {
	GridSlice,
	HeroSlice,
	NavigationItem,
	ProjectListSlice,
	SectionSlice,
};

export const components = {
	grid_slice: GridSlice,
	hero_slice: HeroSlice,
	navigation_item: NavigationItem,
	project_list_slice: ProjectListSlice,
	section_slice: SectionSlice,
};
